language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - libwpd-tools
cache:
  directories:
  - $HOME/.m2
install: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V -U
after_success:
  - mvn clean test jacoco:report coveralls:report
